### PR TITLE
Add support to pass tokens

### LINKED ISSUE #43: Passing original JWT through as a header
Would it be possible to pass the original JWT (from the openid provider) back as a header from the validate request?

I'm trying to use nginx/lasso in front of the istio gateway, and if I could use lasso to do the openid redirection and pass on the jwt to istio, I could then use istio authorization.

### LINKED ISSUE #74: Difference with pusher oauth proxy and how to validate a request directly from an application
Hi,

We are experimenting with vouch to secure some of our internal services and are wondering the reasons behind your approach to build this library. After some searching we also found https://github.com/pusher/oauth2_proxy which is quite similar but seems to be more mature. Could you explain more the rationale around vouch proxy and maybe the differences with other solutions. We are just curious :)

### PR DESCRIPTION
**Pull request by artagel**
I believe this fixes #74, by adding the support to pass tokens to downstream apps.  
Fixes #43 
I also believe this is a more complete implementation of #71, which was focused on ADFS.  This works for all providers.

### CODE REVIEW

**Comment by bnfinet** [comment]
@artagel did you mean to close the PR or is that GitHub being too smart for us.

Sorry for the delay in reviewing.

**Comment by artagel** [comment]
/sigh..  no :)

**Comment by bnfinet** [comment]
:)

**Comment by karthikv2k** [comment]
I am looking forward to get this feature. This is useful for securing services running in https://cloud.google.com/run/ that currently needs a [header](https://cloud.google.com/run/docs/securing/authenticating) with a JWT.

**Comment by karthikv2k** [comment]
Thanks for the PR @artagel

**Comment by bnfinet** [comment]
@karthikv2k have you confirmed that the PR works well for that config?  If not, would you be in a position to test that?

**Comment by karthikv2k** [comment]
@bnfinet I tested by running vouch proxy locally and connecting it a cloud run service and it works :) Next step is to run the vouch proxy itself as a cloud run service and test. I will get that done by tomorrow. 
The end result will have two services, one Nginx+Vouch and other is the destination service. In this way, the destination service run can use cloud run's IAM policy to authorize users for each service separately. Nginx and vouch does the job of reverse proxy, oauth flow, and passing the user's JWT token.

**Comment by karthikv2k** [comment]
@bnfinet I tested this PR in cloud run (as described in my prev comment) and it works.

**Comment by bnfinet** [comment]
Thanks so much for doing that @karthikv2k

Much appreciate!

**Comment by karthikv2k** [comment]
https://github.com/karthikv2k/oauth_reverse_proxy has the config to work with. 
Any help I can do to get this PR merged?

**Comment by bnfinet** [comment]
@karthikv2k can you please test the branch `artagel-add_support_to_pass_tokens`

we're getting closer to full merge :)

**Comment by karthikv2k** [comment]
@bnfinet, I am able to test artagel-add_support_to_pass_tokens and it works as expected. Updated the setup details in https://github.com/karthikv2k/oauth_reverse_proxy

**Comment by bnfinet** [comment]
Much appreciated!

I'm traveling through tomorrow and will look again when I've returned.

**Pull request merged**
