### PR TITLE
Update systemd configs to start at boot time

### PR DESCRIPTION
**Pull request by woneill**
The current configurations won't start vouch-proxy after a system reboot

### CODE REVIEW

**Comment by bnfinet** [comment]
@woneill thanks for the contribution

Is there a reason not to use the `default` runlevel?

**Comment by woneill** [comment]
@bnfinet To be honest, I'm not sure! I changed it based on the other systemd configs I saw on our system.

I looked into what the difference is between `default.target` and `multi-user.target` was. It sounds like `default.target` is usually an alias for either `graphical.target` or `multi-user.target` so that change might not be needed.

**Comment by bnfinet** [comment]
@woneill thanks for checking..

I'm not sure who might be running VP on their laptop but I bet they're out there. :)

With that adjustment I'm happy to merge.

**Comment by woneill** [comment]
@bnfinet Thanks for the merge! I'm sorry I misunderstood that you were asking for me to update the runlevel- I've come across Xwindows running on rackmounted servers so I don't discount what kinds of crazy things people do :)

**Pull request merged**
