### PR TITLE
Update readme with openresty examples

### PR DESCRIPTION
**Pull request by artagel**
With OpenResty, we can offload all authorization functions from vouch and keep it lean and focused.  I think we should provide a couple of common examples to provide to users.  
The readme is starting to get busy... perhaps it is time for a wiki, and we can add it there instead?

### CODE REVIEW

**Comment by bnfinet** [comment]
I'm going to truncate the examples a bit so it's not redudant, with the existing nginx example

would you care to host a gist of the original which we would link to in the README?

**Comment by bnfinet** [comment]
@artagel I made some adjustments when I merged, please do take a look and let me know what you think

**Comment by artagel** [comment]
I think it all looks good.

**Comment by bjornicus** [comment]
> I'm going to truncate the examples a bit so it's not redundant with the existing Nginx example
> 
> would you care to host a gist of the original which we would link to in the README?

Did that gist ever get created?  I tried pasting the lua snippets into my nginx config and it's not working; I don't see how it's calling vouch at all so I suspect I'm missing some important context which the full config would make clear.

**Comment by artagel** [comment]
I have some better formatted examples I’ll try to push this weekend. 
You need to ensure you use openresty, which is nginx compiles with lua, otherwise nothing will work :)

**Comment by artagel** [comment]
#137 Had the examples I was talking about.

**Comment by bjornicus** [comment]
Yes, definitely using openresty :)

Thanks, these full examples are exactly I was hoping existed.

**Pull request merged**
