### PR TITLE
Enable Azure AD v2 tokens

### PR DESCRIPTION
**Pull request by simongottschlag**
Changes:
* Add `oauth.azure_token` (`access_token` and `id_token` are possible configurations)
* Use `preferred_username` if UPN is empty

Tries to fix: https://github.com/vouch/vouch-proxy/issues/314

### CODE REVIEW

**Comment by simongottschlag** [comment]
@bnfinet would it be possible to add the label “hacktoberfest-accepted” to this PR (if it’s accepted)?

**Comment by bnfinet** [comment]
@simongottschlag Sorry for the delay in reviewing.  I should have some time over these next few days to pay attention to the outstanding PRs.

Is this no longer a viable solution?  Was curious why you closed the PR.

**Comment by simongottschlag** [comment]
@bnfinet I was cleaning up all abandoned tasks and PRs I had 😊 I've reopened it again!

**Comment by xtra-be** [comment]
yes please merge, rather have this in main branch than maintain a custom build

**Comment by iamareuben** [comment]
I have pulled this code and tested it, but a bug was introduced into pkg/cfg/oauth.go during a merge (commit 2175fcb) where configureOauthClient() is no longer being called, which leads to a panic during login.

This is pretty straightforward to fix, but I can't fork a PR, and I'm not sure on the etiquette of just copying @simongottschlag changes into my own fork and submitting a PR.  As it's only one line, it's a simple patch:

`diff --git a/pkg/cfg/oauth.go b/pkg/cfg/oauth.go
index 40dc430..b3d2b08 100644
--- a/pkg/cfg/oauth.go
+++ b/pkg/cfg/oauth.go
@@ -143,6 +143,7 @@ func setProviderDefaults() {
                configureOAuthClient()
        } else if GenOAuth.Provider == Providers.Azure {
                setDefaultsAzure()
+               configureOAuthClient()
        } else if GenOAuth.Provider == Providers.IndieAuth {
                GenOAuth.CodeChallengeMethod = "S256"
                configureOAuthClient()`

After that fix, the login flow works perfectly for Azure, both for guest users (fixing #314 ) and full tenant users.  Full log with a simple example config is available at https://gist.github.com/iamareuben/540e1b0b170abab0f0df1a3807538967

Please note that for guest user login to work with this setup, an extra claim needs to be set up in the Azure AD portal for preferred_username (screenshot attached).  As per your config.yml file, this can either be set up as a id_token or an access_token

Let me know if any further info is required to test out this PR.  VP is an awesome piece of software which makes deploying internal web apps for my business super easy so I'm keen to contribute however I can.

Azure Portal Screenshot

**Comment by bnfinet** [comment]
thanks for the contribution and analysis @iamareuben 

I'll add that patch to the PR in the coming days, push to Simon's branch and then ask you to test again.

Thanks also for the kind words and the offer to help.  Always appreciated.

**Comment by acm-073** [comment]
Also tested this PR, it works great. See log file here: https://gist.github.com/acm-073/c7d91bca67c882c1e22e2aa8b4499bc4

I would really be glad to see this merged.

**Comment by bnfinet** [comment]
Thanks @acm-073,

Just to clarify, you made the adjustment to the code that's suggested by @iamareuben prior to generating your log, is that correct?

**Comment by acm-073** [comment]
@bnfinet that change is already in git, see commit https://github.com/vouch/vouch-proxy/pull/320/commits/6d8b79ac52ccc6f1eaee4151d3e227dcb984be43

I just checked out HEAD of branch https://github.com/simongottschlag/vouch-proxy/tree/azureadv2 and used docker build to build the image.

**Comment by bnfinet** [comment]
merged!

@iamareuben @acm-073 @simongottschlag thanks all for the collective effort

**Comment by acm-073** [comment]
@bnfinet great, thanks!

**Pull request merged**
