### PR TITLE
Added support for a custom 'relying party identifier' in ADFS

### PR DESCRIPTION
**Pull request by Herbrant**
Added support for a custom 'relying party identifier' in ADFS configuration

### CODE REVIEW

**Comment by mario-tux** [comment]
@bnfinet Could you provide a feedback on the PR?

**Comment by bnfinet** [comment]
@mario-tux @Herbrant thank you for the PR and for contributing to VP.

Please...
* add `relying_party_id` to `config/config.yml_example` including documentation of it being an ADFS only feature
* add documentation of it's environmental variable to `config/config.yml_example`
* improve the tests for env vars to include the environmental variable.
* add a link to VP GH issue #189 in `config/config.yml_example_adfs` to provide context

**Comment by Herbrant** [comment]
@bnfinet thank you for the review. I will whatever you asked for. I have only one question on the first point: what should I add in `config/config.yml.example`? Because there is no example in that file on adfs.

**Comment by bnfinet** [comment]
thanks @Herbrant 

I'm not sure I have the best answer for what to add to `config/config.yml.example`.  The overarching concept is that all of VPs configuration options should be documented there for consistency.  If you'd like to add a new stanza for ADFS that seems fine.

**Comment by Herbrant** [comment]
Ok I will, thanks again!

**Comment by Herbrant** [comment]
@bnfinet I think I've done. Please let me know if there is anything else to do.

**Comment by mario-tux** [comment]
@bnfinet does the PR revision satisfy your requests?

**Comment by bnfinet** [comment]
@Herbrant @mario-tux thanks for the contribution to VP and your patience

**Pull request merged**
