### PR TITLE
Support tokens/cookies over 4096 bytes

### PR DESCRIPTION
**Pull request by artagel**
At some point, it could become possible to exceed the 4096(ish) byte size limit on cookies.  In order to address this, I've reworked the cookie functions to detect this situation, and split the cookies accordingly, and reassemble them again into a useable compressed token string.

### CODE REVIEW

**Comment by bnfinet** [comment]
I've been down this path a bit before for another project.  Safari holds a limit of 4096 for all cookies in the domain as per the spec, including iPhone iirc.

https://www.lifewire.com/cookie-limit-per-domain-3466809

The greater threat may be the session cookie and the jwt cookie overlapping perhaps, though assuming cookies are LIFO we're probably fine since they're used in series.  Probably should not set the domain on the session cookie which will default to the Vouch domain.

**Comment by artagel** [comment]
yes, you are right.  I just tried a 12k cookie on chrome that worked on Safari, and doesn't work.

**Comment by bnfinet** [comment]
Looks like, Safari mobile is 4093
http://browsercookielimits.squawky.net/

Can the warning message offer the current cookie size?

**Comment by artagel** [comment]
> Can the warning message offer the current cookie size?

I do provide it if the cookie is over 4000 bytes, but i'll include it in the warning also.

**Pull request merged**
