### PR TITLE
add alpine dockerfile

### PR DESCRIPTION
**Pull request by simongottschlag**
More info here: https://github.com/vouch/vouch-proxy/issues/73

### CODE REVIEW

**Comment by bnfinet** [comment]
thanks so much @simongottschlag ,

Looks pretty good

Can we use `ENTRYPOINT` instead of `CMD` to be consistent with the main `DOCKERFILE`?

IIRC you'd like to be able to run a shell inside of the container for testing.  is that right?

I have a snippet in my `.bash_aliases` with `dbash` that I often use to test containers...
```
    function  dbash {
         echo $PWD;
         local IMAGE=$1; shift;
         docker run --rm -i -t -v ${PWD}:/opt/pwd -e TERM=xterm --workdir=/opt/pwd --entrypoint /bin/bash $IMAGE 
    }
    complete -F _docker_images dbash
```

**Comment by simongottschlag** [comment]
I wasn't able to exec into the container when using ENTRYPOINT in Kubernetes, but that may be me doing it wrong.

**Comment by bnfinet** [comment]
Here's good info on getting a shell in a container.  Be sure the container is already running.
https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/

using ENTRYPOINT is the preferred pattern...
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

**Comment by simongottschlag** [comment]
changed to entrypoint 👍

**Pull request merged**
