### PR TITLE
Add env var support

### PR DESCRIPTION
**Pull request by napcae**
Addresses https://github.com/vouch/vouch-proxy/issues/132

### CODE REVIEW

**Comment by bnfinet** [comment]
thanks for starting this effort @napcae 

Will you be able to put more effort into this branch?

**Comment by napcae** [comment]
Hey @bnfinet, yes I'm willing to but I have a problem understanding how/why the oath key is not read by viper. I asked in IRC but there was no answer thats why there are no new pushes so far.

**Comment by bnfinet** [comment]
as discussed on IRC we will need to add a `defaults.yml` file to the `cfg.go` setup so that `viper` can seed it's namespace with variable names from `defaults.yml`.  `viper` will not look for an environmental variable unless it knows the name to look for. `viper` cannot pull all environmental variables in `$VOUCH_*`

**Comment by bnfinet** [comment]
nope, haven't looked at it yet.  I'm devoted to another project this week and then I'm off to a conference.  Next week looks a bit better.

**Comment by bnfinet** [comment]
Thanks for the contribution @napcae and sorry for the delay in reviewing.

Regarding this direction from the README: 
"you still need to copy the default config.yml since viper [needs this variables set](https://github.com/spf13/viper/issues/584) before you can override them"

I think that...

It should "just work".  If you set an Environmental Variable that conforms to the naming convention, then you're done.  This will save much effort for those using Docker Containers since you won't need to map in any config.  Even if a config is available and is successfully read I feel that the environmental variable should override.

`default.yml` should probably by `.defaults.yml` and it should have a comment at the top that explains that it is for this specific use case, not meant for general consumption.  All other comments should be stripped.

`.defaults.yml` should have values which are consistent with the ones set by `cfg.SetDefaults()`

`cfg.SetDefaults()` should be audited and any values which can be replaced by just reading them from `.defaults.yml` would be preferable.

A log WARN message of some sort should be printed if the config changes (test the config before and after the env load event)

Thanks againa and do let me know your thoughts.

**Comment by bnfinet** [comment]
@napcae I'm going to close this for now.

I'm sure what I suggested is a bit more than you wanted to sign up for with this PR.  Of course if that is not the case do let me know and I'd be happy to reopen the PR or continue the discussion in #132. 

Thanks again for putting the effort into VP.

**Pull request closed without merging**
