### PR TITLE
Add ptokens to ADFS

### PR DESCRIPTION
**Pull request by simongottschlag**
* Updated the ADFS part to be able to pass through idtoken/accesstoken to nginx.
* Changed body variable name to data to conform with other providers

### CODE REVIEW

**Comment by simongottschlag** [comment]
I will update this PR according to the discussion I had with @artagel here: https://github.com/vouch/vouch-proxy/commit/e24bd0276b1d57459fc9846266e745ad250415e2#r35004667

**Comment by simongottschlag** [comment]
Noticed that a changed needed for ADFS wasn't present. Added resource to the redirect.

**Comment by bnfinet** [comment]
thanks for the contributions @simongottschlag and for continuing to help maintain ADFS support in Vouch Proxy.

Hope you're doing well!

**Comment by simongottschlag** [comment]
Hi Benjamin! @bnfinet 

No problem at all. I'm just happy that it's included in the main release - which means I won't have to keep a fork updated :)

Keep up the great work and ping me if there's something I can do. (with my extremely limited Golang-skills)

**Pull request merged**
