### PR TITLE
More robust parsing of url param to login

### LINKED ISSUE #281: Vouch proxy fails if URL is correctly escaped in nginx conf
Consider the following nginx configuration, which works:

```
location @unauthenticatedLoginRedirect {
	return 302 https://login.$http_host/login?url=https://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
}
```

and the following, which doesn't:

```
location @unauthenticatedLoginRedirect {
	return 302 https://login.$http_host/login?url=https%3a%2f%2f$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
}
```

These two URLs are the same except that:

 * The first one is not a valid URL according to [RFC 3986 § 2.2](https://tools.ietf.org/html/rfc3986#section-2.2), but it works in Vouch 
 * The second one is a correct percent-encoding of the first URL and is valid according to the RFC, but it doesn't work in Vouch

The reason that the latter doesn't work is that vouch (starting with a353c1981cb2bda47c575f265299640b64506b17) makes a questionable attempt to correctly interpret invalid URLs coming from nginx. Specifically, it attempts to allow URLs such as

```
login?url=x?p1=1&p2=2&vouch-failcount=q
```

in which `p1` and `p2` are supposed to be a part of `url`. These URLs are semantically incorrect and should be 

```
login?url=x%3fp1%3d1%26p2%3d2&vouch-failcount=q
```

That is, **all** of `?=&` must be percent encoded to make this semantically correct per the RFC. 

Vouch's attempt at being liberal in what it accepts leads to a failure with URLs that *are* semantically correct; specifically: `getValidRequestedURL` [calls](https://github.com/vouch/vouch-proxy/blob/dfbd013f1043ba9548b3cedee466b9993210a3c4/handlers/login.go#L122) `HasPrefix` to check for http:// or https://, and fails on a correctly encoded URL.

I am going to argue that this approach to correctly interpreting invalid URLs should be abandoned in favor of a different approach, as the current approach has multiple flaws. In addition to the problem I am reporting here, the current approach taken by `getValidRequestedURL` will fail in the following cases:

 * the `url` param is not the first param, because of [this code](https://github.com/vouch/vouch-proxy/blob/dfbd013f1043ba9548b3cedee466b9993210a3c4/handlers/login.go#L113)
 * the `vouch-failcount` param is not the second param because of [this code](https://github.com/vouch/vouch-proxy/blob/dfbd013f1043ba9548b3cedee466b9993210a3c4/handlers/login.go#L112)

In other words, the current approach breaks semantics of URLs in multiple ways, which is bad.

Instead, I recommend the following approach, which will work in all the above cases *and* maintain the goal of handling URL params which are not correctly encoded, but can be reasonably interpreted. Consider the following URL as an example:

```
login?url=x?p1=1&p2=2&vouch-failcount=q
```

 * Do not access `RawQuery` of `r.URL`
 * Instead, access the parsed query, which will produce `{url: "x?p1=1", p2: "2", vouch-failcount: "q"}`
 * Enumerate all the parameters in the parsed query and identify all that do not belong to vouch (which I think is everything that doesn't start with `vouch` or `X-Vouch`), here `p2`
 * Add all of those non-vouch parameters to the URL in the `url` parameter, here obtaining `{url: "x?p1=1&p2=2", vouch-failcount: "q"}`
 * Proceed as before to validate the URL

Note that this *will* interpret 

```
login?p3=3&url=x?p1=1&p2=2&vouch-failcount=q
```

to have the url `x?p1=1&p2=2&p3=3`, which I consider questionable.

A more stringent approach that still handles the intended case would only move URL params between `url` and the first vouch param into `url`, thereby turning this example into `{p3: "3", url: "x?p1=1&p2=2", vouch-failcount: "q"}`. I would lean towards rejecting that URL as `p3` is not a valid vouch `/login` param.

### PR DESCRIPTION
**Pull request by airbornemint**
Fixes #281

### CODE REVIEW

**Comment by bnfinet** [comment]
@airbornemint I've added a few tests which are based on the README's documentation.  Could you please adjust the code to allow those to pass.

**Comment by airbornemint** [comment]
Done

**Comment by bnfinet** [comment]
this is merged in [v0.16.0](https://github.com/vouch/vouch-proxy/tree/v0.16.0)

perhaps the squash'd merge is preventing it from detecting the merge.

@airbornemint thanks for the code!

**Comment by airbornemint** [comment]
Yeah, probably; I globally disabled squash merging in my git settings because of problems like this 🙂  Yw!

**Pull request closed without merging**
