### PR TITLE
Less aggressive url param parsing

### PR DESCRIPTION
**Pull request by airbornemint**
I relaxed the stray login URL param algorithm; it now detects stray params as before, but doesn't raise an error (they are reported in the log). See #289.

### CODE REVIEW

**Comment by bnfinet** [comment]
@airbornemint thanks again for the contribution.

IMHO `rd` is not a stray param, but is in fact part of the implicit contract between VP and the Nginx ingress.  That's consistent with supporting features that have been documented in the README up until #283.

IIUC if `|| param == 'rd'` is added back in this should be gtg, is that right?

**Comment by airbornemint** [comment]
I disagree with your assessment, but I could be wrong. The reason that I believe that `rd` is a stray param is that, as I understand it:

 * `rd` is used by nginx ingress *before* it is passed to VP
 * VP `login` does not use `rd` directly
 * VP `login` does not pass `rd` to anyone else

If it was up to me, nginx ingress would use *and remove* `rd`, but since it doesn't, `login` is stuck having to ignore it.

Other things documented in the README are things that `login` actually makes use of (either directly, or by passing them to the IdP). 

But if you disagree and you add `|| param == 'rd'` back in, okay.

**Comment by bnfinet** [comment]
@airbornemint I'm not sure of the absolute correct behavior and it probably could be improved, this is more along the lines of "don't break userland" which was what @zheker was pointing at with #289 

I don't think `rd` should be logged as "stray" since Nginx Ingress is supported.

In either case this PR does not pass Travis.

If you wanted to pursue a change to Nginx Ingress by opening an issue at https://github.com/kubernetes/ingress-nginx I'd be happy to support your effort where possible.

**Comment by airbornemint** [comment]
Oh yeah, I got distracted from fixing the Travis error, sorry about that. 

Anyway, yeah, I am fine not logging `rd` as stray. Can't work up the energy to open an issue against software I don't even use 🙂

**Comment by bnfinet** [comment]
@airbornemint thanks for the code!

Hope to see you around these parts again soon :)

**Pull request merged**
